# Seed data containing harvested Whitelist (DOAJ) and Blacklist (Beall's List) domains.

DOAJ_JOURNALS = [
    ('mlj.goums.ac.ir', 'Medical Laboratory Journal'),
    ('czasopismanaukowe.mazowiecka.edu.pl', 'Społeczeństwo, Edukacja, Język'),
    ('jurnal.unej.ac.id', 'Computational and Experimental Research in Materials and Renewable Energy'),
    ('theglobaljusticenetwork.org', 'Global justice: Theory, Practice, Rhetoric'),
    ('revistapsicologia.uchile.cl', 'Revista de Psicología'),
    ('journal.um.ac.id', 'Jurnal Pendidikan: Teori, Penelitian, dan Pengembangan'),
    ('nature.com', 'Communications Engineering'),
    ('ama.sgu.ru', 'Античный мир и археология'),
    ('journals.umcs.pl', 'Studia Iuridica Lublinensia'),
    ('academic.oup.com', 'PNAS Nexus'),
    ('mestradoedoutoradoestacio.periodicoscientificos.com.br', 'Revista Adm.Made'),
    ('dergipark.org.tr', 'Ankara Üniversitesi Eğitim Bilimleri Fakültesi Özel Eğitim Dergisi'),
    ('crjim.ub.ac.id', 'Clinical and Research Journal in Internal Medicine'),
    ('russianradiology.ru', 'Вестник рентгенологии и радиологии'),
    ('vcs.pensoft.net', 'Vegetation Classification and Survey (VCS)'),
    ('revistascientificas.filo.uba.ar', 'Patristica et Mediaevalia'),
    ('seer.ufal.br', 'Ciência da Informação em Revista'),
    ('pagepressjournals.org', 'Advances in Oceanography and Limnology'),
    ('revistas.planejamento.rs.gov.br', 'Boletim Geográfico do Rio Grande do Sul'),
    ('ppml.url.tw', 'Journal of Engineering, Project, and Production Management'),
    ('geoproximites.fr', 'GéoProximitéS'),
    ('tlj.usc.ac.ir', 'گردشگری & اوقات فراغت'),
    ('periodicos.ufsc.br', 'Principia: An International Journal of Epistemology'),
    ('jsbs.scholasticahq.com', 'Journal of Small Business Strategy'),
    ('journals.lsu.lt', 'Reabilitacijos Mokslai: Slauga, Kineziterapija, Ergoterapija'),
    ('digitalcommons.unmc.edu', 'Graduate Medical Education Research Journal'),
    ('journals.openedition.org', 'South Asia Multidisciplinary Academic Journal'),
    ('jenci.springeropen.com', 'Journal of the Egyptian National Cancer Institute'),
    ('bctp.knuba.edu.ua', 'Будівельні конструкції. Теорія і практика'),
    ('recacym.org', 'El Cálculo y su Enseñanza'),
    ('tiemposmodernos.org', 'Tiempos Modernos: Revista Electrónica de Historia Moderna'),
    ('revistas.unlp.edu.ar', 'Proyecciones'),
    ('revistasbemsp.com.br', 'Revista de Educação Matemática'),
    ('journal.uny.ac.id', 'Harmoni Sosial: Jurnal Pendidikan IPS'),
    ('ejournal.umpri.ac.id', 'Jurnal Smart'),
    ('journals.sbmu.ac.ir', 'International Clinical Neuroscience Journal'),
    ('journals.lww.com', 'Indian Journal of Dental Sciences'),
    ('cambridge.org', 'European Psychiatry'),
    ('revistas.usach.cl', 'Estudios Avanzados'),
    ('revistas.usp.br', 'Significação: Revista de Cultura Audiovisual'),
    ('rosa.uniroma1.it', 'Fragmenta entomologica'),
    ('lmcs.episciences.org', 'Logical Methods in Computer Science'),
    ('publikasi.mercubuana.ac.id', 'MIX: Jurnal Ilmiah Manajemen'),
    ('ejcrim.com', 'European Journal of Case Reports in Internal Medicine'),
    ('journals.ufs.ac.za', 'Perspectives in Education'),
    ('sciencedirect.com', 'Scientific African'),
    ('sanad.iau.ir', 'Journal of English Language Pedagogy and Practice'),
    ('revistaestudiospoliticaspublicas.uchile.cl', 'Revista Estudios de Políticas Públicas'),
    ('aph.org.br', 'Revista de Homeopatia'),
    ('jouroilcrops.cn', 'Zhongguo youliao zuowu xuebao'),
    ('tribunainternacional.uchile.cl', 'Revista Tribuna Internacional'),
    ('jurnal.umk.ac.id', 'Kredo: Jurnal Ilmiah Bahasa dan Sastra'),
    ('journals.uniurb.it', 'Cultura giuridica e diritto vivente'),
    ('bibliotecavirtual.unl.edu.ar', 'Tópicos'),
    ('jhs.uma.ac.ir', 'Journal of Hyperstructures'),
    ('journal.uad.ac.id', 'Pharmaciana'),
    ('frontiersin.org', 'Frontiers in Conservation Science'),
    ('publicacoes.ispa.pt', 'Análise Psicológica'),
    ('springer.com', 'Living Reviews in Relativity'),
    ('sujo.usindh.edu.pk', 'Asia Pacific'),
    ('cadhd-dr.org', 'Cahiers Africains des Droits de l’Homme et de la Démocratie ainsi que du Développement Durable'),
    ('jed.ut.ac.ir', 'توسعه کارآفرینی'),
    ('htainaction.tums.ac.ir', 'Health Technology Assessment in Action'),
    ('eurogeologists.eu', 'European Geologist'),
    ('plural.upsc.md', 'Plural: History, Culture, Society'),
    ('irsrmjournal.ir', 'مکانیک سنگ'),
    ('ijims.iainsalatiga.ac.id', 'Indonesian Journal of Islam and Muslim Societies'),
    ('revistas.upch.edu.pe', 'Revista Herediana de Rehabilitación'),
    ('sophia.ups.edu.ec', 'Sophía: Colección de Filosofía de la Educación'),
    ('ijnmr.net', 'Indian Journal of Neonatal Medicine and Research'),
    ('revistas.udesc.br', 'DAPesquisa'),
    ('ph02.tci-thaijo.org', 'Food Agricultural Sciences and Technology (FAST)'),
    ('keaipublishing.com', 'Tropical Cyclone Research and Review'),
    ('czasopisma.ignatianum.edu.pl', 'Multidisciplinary Journal of School Education'),
    ('journal.yykxjz.cn', 'Progress in Fishery Sciences'),
    ('aapc.khu.ac.ir', 'حسابداری ارزشی و رفتاری'),
    ('economiatyp.uam.mx', 'Economía Teoría y Práctica'),
    ('journals.akademicka.pl', 'Politeja'),
    ('painmedicine.org.ua', 'Медицина болю'),
    ('sjme.journals.sharif.edu', 'مهندسی مکانیک شریف'),
    ('journalofcoms.com', 'Journal of Current Oncology and Medical Sciences'),
    ('integrative-journal.com', 'International Journal of Integrative Psychotherapy'),
    ('jccnc.iums.ac.ir', 'Journal of Client-centered Nursing Care'),
    ('sciendo.com', 'Arhiv za Higijenu Rada i Toksikologiju'),
    ('onlinelibrary.wiley.com', 'Case Reports in Veterinary Medicine'),
    ('ieeexplore.ieee.org', 'Big Data Mining and Analytics'),
    ('revistapolis.ro', 'Polis: Revista de Stiinte Politice'),
    ('tandfonline.com', 'Technology and Innovation'),
    ('pp.bme.hu', 'Periodica Polytechnica: Mechanical Engineering'),
    ('ejournal.uiidalwa.ac.id', "Al Mu'azarah"),
    ('bulletin.ssmu.ru', 'Бюллетень сибирской медицины'),
    ('apcz.umk.pl', 'Biuletyn Polskiej Misji Historycznej'),
    ('dovepress.com', 'Patient Preference and Adherence'),
    ('evidencia.org.ar', 'Evidencia. Actualización en la Práctica Ambulatoria'),
    ('jnc.psychopen.eu', 'Journal of Numerical Cognition'),
    ('science.lpnu.ua', 'Менеджмент та підприємництво в Україні: етапи становлення і проблеми розвитку'),
    ('jrp.uma.ac.ir', 'Journal of Research in Psychopathology'),
    ('medicinauniversitaria.org', 'Medicina Universitaria'),
    ('uej.undip.org.ua', 'Український педагогічний журнал'),
    ('revista.seminarioconciliardemedellin.org', 'Revista Seminario Mayor de Medellín'),
    ('jme.biam.ac.cn', 'Cailiao gongcheng'),
    ('archpublichealth.biomedcentral.com', 'Archives of Public Health'),
    ('rev-sep.ec', 'Revista Ecuatoriana de Pediatría'),
    ('hrcak.srce.hr', 'Libri Oncologici'),
    ('lib.jucs.org', 'Journal of Universal Computer Science'),
    ('berkalahayati.org', 'Journal of Biological Researches'),
    ('eo.bioscientifica.com', 'Endocrine Oncology'),
    ('revistas.udistrital.edu.co', 'Revista Científica'),
    ('revistas.ucv.edu.pe', 'UCV-Scientia'),
    ('revistas.uniandes.edu.co', 'Naturaleza y Sociedad: Desafíos Medioambientales'),
    ('fysioterapeuten.no', 'Fysioterapeuten'),
    ('jaaralexu.journals.ekb.eg', 'Mağallaẗ Taṭbīqāt ʿulūm Al-Rīyāḍaẗ'),
    ('emeraldgrouppublishing.com', 'Tourism Critiques'),
    ('revistaderecho.ucn.cl', 'Revista de Derecho (Coquimbo)'),
    ('journal.uokufa.edu.iq', 'Kufa Journal for Nursing Sciences'),
    ('journals.library.brandeis.edu', 'Caste'),
    ('dalps.tirant.com', 'Derecho Animal'),
    ('eppcgs.org', 'Earth and Planetary Physics'),
    ('jurnal.ugm.ac.id', 'Journal of Internet and Software Engineering'),
    ('qfi-oz.de', 'Qualifizierung für Inklusion'),
    ('linguarumuniverse.weebly.com', 'Linguarum Universe'),
    ('jpl.letras.ulisboa.pt', 'Journal of Portuguese Linguistics'),
    ('sc.journals.umz.ac.ir', 'Journal of Genetic Resources'),
    ('en.china-fishery.cn', 'Shuichan Xuebao'),
    ('ejurnal.teknokrat.ac.id', 'Jurnal Teknoinfo'),
    ('rhema-journal.com', 'Rhema. Рема'),
    ('bmcmedgenomics.biomedcentral.com', 'BMC Medical Genomics'),
    ('ejournal.sttii-yogyakarta.ac.id', 'Predica Verbum'),
    ('revistas.uexternado.edu.co', 'Sotavento MBA'),
    ('arsmedica.cl', 'ARS Medica'),
    ('arabmediasociety.com', 'Arab Media and Society'),
    ('tet.rkk.hu', 'Tér és Társadalom'),
    ('cswr.columbia.edu', 'Columbia Social Work Review'),
    ('ir.library.louisville.edu', 'The University of Louisville Journal of Respiratory Infections'),
    ('iucrdata.iucr.org', 'IUCrData'),
    ('publichealthtoxicology.com', 'Public Health and Toxicology'),
    ('periodicos.ufpb.br', 'Teoria e Prática em Administração'),
    ('ojs.udb.ac.id', 'Jurnal Keperawatan Duta Medika'),
    ('unissa.edu.bn', "International Journal of 'Umrānic Studies"),
    ('rivista-statistica.unibo.it', 'Statistica'),
    ('jurnal.ar-raniry.ac.id', 'Elkawnie: Journal of Islamic Science and Technology'),
    ('mnase.journals.ekb.eg', 'Maǧallaẗ Naẓariyāt wa Taṭbīqāt Al-Tarbiyyaẗ Al-Badaniyyaẗ waʿulūm Al-Rīyāḍaẗ'),
    ('journals.aua.ke', 'Pan-African Journal of Health and Environmental Science'),
    ('trilogi.ac.id', 'JISA (Jurnal Informatika dan Sains)'),
    ('energy-cie.ro', 'Journal of Sustainable Energy'),
    ('ojs.unito.it', 'Gli Spazi della Musica'),
    ('bmjdigitalhealth.bmj.com', 'BMJ Digital Health & AI'),
    ('revistadigital.uce.edu.ec', 'Revista Textos y Contextos'),
    ('slovenskapediatrija.si', 'Slovenska pediatrija'),
    ('przeglad.amu.edu.pl', 'Przegląd Politologiczny'),
]

BEALLS_JOURNALS = [
    ('1088.email', '1088 Email Press'),
    ('2425publishers.org', '2425 Publishers'),
    ('5thpublisher.com', 'The 5th Publisher'),
    ('abcjournals.net', 'ABC Journals'),
    ('ampublisher.com', 'A M Publishers'),
    ('abhinavjournal.com', 'Abhinav'),
    ('academeresearchjournals.org', 'Academe Research Journals'),
    ('academiapublishing.org', 'Academia Publishing'),
    ('academiaresearch.org', 'Academia Research'),
    ('academiascholarlyjournal.org', 'Academia Scholarly Journals'),
    ('aabri.com', 'Academic and Business Research Institute'),
    ('acascipub.com', 'Academic and Scientific Publishing'),
    ('ph.academicdirect.org', 'Academic Direct Publishing House'),
    ('academicjournals.org', 'Academic Journals'),
    ('acjar.org', 'Academic Journals and Research'),
    ('academicjournalsonline.co.in', 'Academic Journals Online'),
    ('academicjournalsinc.com', 'Academic Journals, Inc.'),
    ('akrpub.com', 'Academic Knowledge and Research Publishing'),
    ('academicoasis.org', 'Academic Organization for Advancement of Strategic and International Studies'),
    ('acadpubl.eu', 'Academic Publications, Ltd.'),
    ('arseam.com', 'Academic Research in Science, Engineering, Art and Management'),
    ('academicresearchjournals.org', 'Academic Research Journals'),
    ('acrpub.com', 'Academic Research Publishers'),
    ('arpapress.com', 'Academic Research Publishing Agency'),
    ('arpgweb.com', 'Academic Research Publishing Group'),
    ('acadrp.org', 'Academic Research Publishing House'),
    ('academic-publishing-house.com', 'Academic Scholars Publishing House'),
    ('ijaponline.org', 'Academic Sciences'),
    ('academicstar.us', 'Academic Star Publishing Company'),
    ('astarstore.us', 'Academic Star Publishing Company [alt]'),
    ('academicwebpublishers.org', 'Academic Web Publishers'),
    ('awer-center.org', 'Academic World Education & Research Center'),
    ('arcjournals.org', 'Academicians’ Research Center/ARC Journals'),
    ('academicsworld.org', 'Academics World'),
    ('aelsindia.com', 'Academy for Environment and Life Sciences'),
    ('academyjournals.net', 'Academy Journals'),
    ('abrmr.com', 'Academy of Business & Retail Management'),
    ('absronline.org', 'Academy of Business & Scientific Research'),
    ('academyirmbr.com', 'Academy of International Research in Management and Business Realities'),
    ('akpinsight.webs.com', 'Academy of Knowledge Process'),
    ('scienceengineeringacademy.org', 'Academy of Science and Engineering'),
    ('asss-web.com', 'Academy of Science and Social Science'),
    ('asaarjournals.com', 'Academy of Scientific and Applied Research'),
    ('academypublish.org', 'Academy Publish'),
    ('accessinterjournals.org', 'Access International Journals'),
    ('accessjournals.org', 'Access Journals'),
    ('accesspublishers.org', 'Access Publishers'),
    ('ghrnet.org', 'ACT Publishing'),
    ('actascientifica.com', 'Acta Scientifica'),
    ('adpublication.org', 'AD Publication'),
    ('adpublications.org', 'AD Publications'),
    ('ada-lovelace.co.uk', 'Ada Lovelace Publications'),
    ('aeirc-edu.com', 'Advance Educational Institute & Research Centre'),
    ('advancejournals.org', 'Advance Journals'),
    ('aicit.org', 'Advanced Institute of Convergence Information Technology'),
    ('advancedjournals.org', 'Advanced Journals'),
    ('advancedresearchjournals.org', 'Advanced Research Journals'),
    ('adrpublications.in', 'Advanced Research Publications'),
    ('advancedscholarsjournals.org', 'Advanced Scholars Journals'),
    ('asetrc.org', 'Advanced Science and Engineering Technology Institute'),
    ('advancedscienceresearchjournals.org', 'Advanced Science Research Journals'),
    ('atscience.org', 'Advanced Technology & Science'),
    ('aditisci.com', 'Advancement and Development in Technology International'),
    ('ajourjournals.com', 'Advancements in Science'),
    ('adyanacademicpress.com', 'Adyan Academic Press'),
    ('aensiweb.com', 'American-Eurasian Network for Scientific Information'),
    ('afrrevjo.net', 'African Research Review'),
    ('agialpress.com', 'AgiAl Publishing House'),
    ('agropub.com', 'Agropub'),
    ('ainstin.com', 'AINSTIN Knowledge Hub'),
    ('airccse.org', 'AIRCC Publishing Corporation'),
    ('aizeonpublishers.net', 'Aizeon Publishers'),
    ('allbertscience.com', 'Albert Science International Organization'),
    ('alliedacademies.org', 'Allied Academies'),
    ('alliedjournals.com', 'Allied Journals'),
    ('ambitjournals.org', 'Ambit Journals'),
    ('amepc.org', 'AME Publishing Company'),
    ('aasrc.org', 'American Academic & Scholarly Research Center'),
    ('aascit.org', 'American Association for Science and Technology'),
    ('amjournals.org', 'American Journal'),
    ('aripd.org', 'American Research Institute for Policy Development'),
    ('arjonline.org', 'American Research Journals'),
    ('arepub.com', 'American Research Publications'),
    ('asraresearch.org', 'American Scholarly Research Association'),
    ('aspbs.com', 'American Scientific Publishers'),
    ('americanscientificresearchjournals.org', 'American Scientific Research Journals'),
    ('asrn.org', 'American Society of Registered Nurses'),
    ('as-se.org', 'American Society of Science and Engineering'),
    ('vkingpub.com', 'American V-King Scientific Publishing'),
    ('aessangli.in', 'Amoghsiddhi Education Society/AES/AES Journals in Engineering Technology, Management, and Sciences/AES E-JOURNALS'),
    ('ejournal.aessangli.in', 'Amoghsiddhi Education Society/AES/AES Journals in Engineering Technology, Management, and Sciences/AES E-JOURNALS [alt]'),
    ('andrewjohnpublishing.org', 'Andrew John Publishing Inc.'),
    ('annexpublishers.com', 'Annex Publishers'),
    ('ansinet.com', 'Asian Network for Scientific Information'),
    ('domainsmoon.com', 'Antarctic Journals'),
    ('aperito.org', 'Aperito Online Publishing'),
    ('apexjournal.org', 'Apex Journal'),
    ('applied-science-innovations.com', 'Applied Science Innovations'),
    ('apst.co.in', 'APST Publication'),
    ('arabianjbmr.com', 'Arabian Group of Journals'),
    ('puneresearch.com', 'Aradhya International Publication'),
    ('aeph.in', 'Archers & Elevators Publishing House'),
    ('archyworld.com', 'Archyworld'),
    ('arpnjournals.com', 'ARPN Journals'),
    ('aspublishers.com', 'AS Publishers'),
    ('asdpub.com', 'ASD Publisher'),
    ('ashdin.com', 'Ashdin Publishing'),
    ('ashese.co.uk', 'AshEse Visionary'),
    ('apamr.org', 'Asia-Pacific Association of Medical Research'),
    ('apiar.org.au', 'Asia Pacific Institute of Advanced Research'),
    ('asianacademicresearch.org', 'Asian Academic Research Associates'),
    ('aarpub.com', 'Asian and American Research Publishing Group'),
    ('aessweb.com', 'Asian Economic and Social Society'),
    ('asianonlinejournals.com', 'Asian Online Journal Publishing Group'),
    ('ajouronline.com', 'Asian Online Journals'),
    ('asianpharmaonline.org', 'Asian Pharma Press'),
    ('asianpubs.org', 'Asian Publication Corporation'),
    ('aijsh.org', 'Asian Research Consortium'),
    ('asian-transactions.org', 'Asian Transactions'),
    ('aarf.asia', 'Associated Asia Research Foundation'),
    ('asers.eu', 'Association for Sustainable Education, Research and Science'),
    ('theaceee.org', 'Association of Computer Electronics and Electrical Engineers'),
    ('anahei.org', 'Association of North America Higher Education International'),
    ('asterpublications.org', 'Aster Publications'),
    ('astonjournals.com', 'AstonJournals'),
    ('athalgroup.com', 'Athal Press & Media'),
    ('atharvapub.com', 'Atharva Scientific Publications'),
    ('atiner.gr', 'Athens Institute for Education and Research'),
    ('atlas-publishing.org', 'Atlas Publishing, LP'),
    ('chesci.com', 'Aufau Periodicals'),
    ('austinpublishinggroup.org', 'Austin Publishing Group'),
    ('acrd.net.au', 'Australasian Centre for Research and Development'),
    ('aabss.org.au', 'Australian Academy of Business and Social Sciences'),
    ('aabl.com.au', 'Australian Academy of Business Leadership'),
    ('aiac.org.au', 'Australian International Academic Centre Pty. Ltd.'),
    ('ausinternationaljournals.com.au', 'Australian International Research Consortium'),
    ('scie.org.au', 'Australian Society for Commerce Industry & Engineering'),
    ('aeuso.org', 'Austrian E-Journals of Universal Scientific Organization'),
    ('autpub.org', 'Austrian Scientific Publication House'),
    ('avantipublishers.com', 'Avanti Publishers.com'),
    ('avensonline.org', 'Avens Publishing Group'),
    ('avestia.com', 'Avestia Publishing'),
    ('avicenapublisher.org', 'Avicena Publisher'),
    ('avidscience.com', 'Avid Science'),
    ('axisjournals.com', 'Axis Journals'),
    ('wjgnet.com', 'Baishideng Publishing Group'),
    ('basharesearch.com', 'Basha Research Corporation'),
    ('basicresearchjournals.org', 'Basic Research Journals'),
    ('bellpress.org', 'Bell Press'),
    ('benthamopen.com', 'Bentham Open'),
]
