# Generated Whitelist and Blacklist

DOAJ_JOURNALS = [
    ('mlj.goums.ac.ir', 'Medical Laboratory Journal'),
    ('czasopismanaukowe.mazowiecka.edu.pl', 'Społeczeństwo, Edukacja, Język'),
    ('jurnal.unej.ac.id', 'Computational and Experimental Research in Materials and Renewable Energy'),
    ('theglobaljusticenetwork.org', 'Global justice: Theory, Practice, Rhetoric'),
    ('revistapsicologia.uchile.cl', 'Revista de Psicología'),
    ('journal.um.ac.id', 'Jurnal Pendidikan: Teori, Penelitian, dan Pengembangan'),
    ('nature.com', 'Communications Engineering'),
    ('ama.sgu.ru', 'Античный мир и археология'),
    ('journals.umcs.pl', 'Studia Iuridica Lublinensia'),
    ('academic.oup.com', 'PNAS Nexus'),
    ('mestradoedoutoradoestacio.periodicoscientificos.com.br', 'Revista Adm.Made'),
    ('dergipark.org.tr', 'Ankara Üniversitesi Eğitim Bilimleri Fakültesi Özel Eğitim Dergisi'),
    ('crjim.ub.ac.id', 'Clinical and Research Journal in Internal Medicine'),
    ('russianradiology.ru', 'Вестник рентгенологии и радиологии'),
    ('vcs.pensoft.net', 'Vegetation Classification and Survey (VCS)'),
    ('revistascientificas.filo.uba.ar', 'Patristica et Mediaevalia'),
    ('seer.ufal.br', 'Ciência da Informação em Revista'),
    ('pagepressjournals.org', 'Advances in Oceanography and Limnology'),
    ('revistas.planejamento.rs.gov.br', 'Boletim Geográfico do Rio Grande do Sul'),
    ('ppml.url.tw', 'Journal of Engineering, Project, and Production Management'),
    ('geoproximites.fr', 'GéoProximitéS'),
    ('tlj.usc.ac.ir', 'گردشگری و اوقات فراغت'),
    ('periodicos.ufsc.br', 'Principia: An International Journal of Epistemology'),
    ('jsbs.scholasticahq.com', 'Journal of Small Business Strategy'),
    ('journals.lsu.lt', 'Reabilitacijos Mokslai: Slauga, Kineziterapija, Ergoterapija'),
    ('digitalcommons.unmc.edu', 'Graduate Medical Education Research Journal'),
    ('journals.openedition.org', 'South Asia Multidisciplinary Academic Journal'),
    ('jenci.springeropen.com', 'Journal of the Egyptian National Cancer Institute'),
    ('bctp.knuba.edu.ua', 'Будівельні конструкції. Теорія і практика'),
    ('recacym.org', 'El Cálculo y su Enseñanza'),
    ('tiemposmodernos.org', 'Tiempos Modernos: Revista Electrónica de Historia Moderna'),
    ('revistas.unlp.edu.ar', 'Proyecciones'),
    ('revistasbemsp.com.br', 'Revista de Educação Matemática'),
    ('journal.uny.ac.id', 'Harmoni Sosial: Jurnal Pendidikan IPS'),
    ('ejournal.umpri.ac.id', 'Jurnal Smart'),
    ('journals.sbmu.ac.ir', 'International Clinical Neuroscience Journal'),
    ('journals.lww.com', 'Indian Journal of Dental Sciences'),
    ('cambridge.org', 'European Psychiatry'),
    ('revistas.usach.cl', 'Estudios Avanzados'),
    ('revistas.usp.br', 'Significação: Revista de Cultura Audiovisual'),
    ('rosa.uniroma1.it', 'Fragmenta entomologica'),
    ('lmcs.episciences.org', 'Logical Methods in Computer Science'),
    ('publikasi.mercubuana.ac.id', 'MIX: Jurnal Ilmiah Manajemen'),
    ('ejcrim.com', 'European Journal of Case Reports in Internal Medicine'),
    ('journals.ufs.ac.za', 'Perspectives in Education'),
    ('sciencedirect.com', 'Scientific African'),
    ('sanad.iau.ir', 'Journal of English Language Pedagogy and Practice'),
    ('revistaestudiospoliticaspublicas.uchile.cl', 'Revista Estudios de Políticas Públicas'),
    ('aph.org.br', 'Revista de Homeopatia'),
    ('jouroilcrops.cn', 'Zhongguo youliao zuowu xuebao'),
    ('tribunainternacional.uchile.cl', 'Revista Tribuna Internacional'),
    ('jurnal.umk.ac.id', 'Kredo: Jurnal Ilmiah Bahasa dan Sastra'),
    ('journals.uniurb.it', 'Cultura giuridica e diritto vivente'),
    ('bibliotecavirtual.unl.edu.ar', 'Tópicos'),
    ('jhs.uma.ac.ir', 'Journal of Hyperstructures'),
    ('journal.uad.ac.id', 'Pharmaciana'),
    ('frontiersin.org', 'Frontiers in Conservation Science'),
    ('publicacoes.ispa.pt', 'Análise Psicológica'),
    ('springer.com', 'Living Reviews in Relativity'),
    ('sujo.usindh.edu.pk', 'Asia Pacific'),
    ('cadhd-dr.org', 'Cahiers Africains des Droits de l’Homme et de la Démocratie ainsi que du Développement Durable'),
    ('jed.ut.ac.ir', 'توسعه کارآفرینی'),
    ('htainaction.tums.ac.ir', 'Health Technology Assessment in Action'),
    ('eurogeologists.eu', 'European Geologist'),
    ('plural.upsc.md', 'Plural: History, Culture, Society'),
    ('irsrmjournal.ir', 'مکانیک سنگ'),
    ('ijims.iainsalatiga.ac.id', 'Indonesian Journal of Islam and Muslim Societies'),
    ('revistas.upch.edu.pe', 'Revista Herediana de Rehabilitación'),
    ('sophia.ups.edu.ec', 'Sophía: Colección de Filosofía de la Educación'),
    ('ijnmr.net', 'Indian Journal of Neonatal Medicine and Research'),
    ('revistas.udesc.br', 'DAPesquisa'),
    ('ph02.tci-thaijo.org', 'Food Agricultural Sciences and Technology (FAST)'),
    ('keaipublishing.com', 'Tropical Cyclone Research and Review'),
    ('czasopisma.ignatianum.edu.pl', 'Multidisciplinary Journal of School Education'),
    ('journal.yykxjz.cn', 'Progress in Fishery Sciences'),
    ('aapc.khu.ac.ir', 'حسابداری ارزشی و رفتاری'),
    ('economiatyp.uam.mx', 'Economía Teoría y Práctica'),
    ('journals.akademicka.pl', 'Politeja'),
    ('painmedicine.org.ua', 'Медицина болю'),
    ('sjme.journals.sharif.edu', 'مهندسی مکانیک شریف'),
    ('journalofcoms.com', 'Journal of Current Oncology and Medical Sciences'),
    ('msgh-journal.com', 'Сучасні дослідження з німецької історії'),
    ('integrative-journal.com', 'International Journal of Integrative Psychotherapy'),
    ('jccnc.iums.ac.ir', 'Journal of Client-centered Nursing Care'),
    ('sciendo.com', 'Arhiv za Higijenu Rada i Toksikologiju'),
    ('onlinelibrary.wiley.com', 'Case Reports in Veterinary Medicine'),
    ('ieeexplore.ieee.org', 'Big Data Mining and Analytics'),
    ('revistapolis.ro', 'Polis: Revista de Stiinte Politice'),
    ('tandfonline.com', 'Technology and Innovation'),
    ('pp.bme.hu', 'Periodica Polytechnica: Mechanical Engineering'),
    ('ejournal.uiidalwa.ac.id', 'Al Mu\'azarah'),
    ('bulletin.ssmu.ru', 'Бюллетень сибирской медицины'),
    ('apcz.umk.pl', 'Biuletyn Polskiej Misji Historycznej'),
    ('dovepress.com', 'Patient Preference and Adherence'),
    ('evidencia.org.ar', 'Evidencia. Actualización en la Práctica Ambulatoria'),
    ('jnc.psychopen.eu', 'Journal of Numerical Cognition'),
    ('science.lpnu.ua', 'Менеджмент та підприємництво в Україні: етапи становлення і проблеми розвитку'),
    ('jrp.uma.ac.ir', 'Journal of Research in Psychopathology'),
    ('medicinauniversitaria.org', 'Medicina Universitaria'),
    ('uej.undip.org.ua', 'Український педагогічний журнал'),
    ('revista.seminarioconciliardemedellin.org', 'Revista Seminario Mayor de Medellín'),
    ('jme.biam.ac.cn', 'Cailiao gongcheng'),
    ('archpublichealth.biomedcentral.com', 'Archives of Public Health'),
    ('rev-sep.ec', 'Revista Ecuatoriana de Pediatría'),
    ('hrcak.srce.hr', 'Libri Oncologici'),
    ('lib.jucs.org', 'Journal of Universal Computer Science'),
    ('berkalahayati.org', 'Journal of Biological Researches'),
    ('eo.bioscientifica.com', 'Endocrine Oncology'),
    ('revistas.udistrital.edu.co', 'Revista Científica'),
    ('revistas.ucv.edu.pe', 'UCV-Scientia'),
    ('revistas.uniandes.edu.co', 'Naturaleza y Sociedad: Desafíos Medioambientales'),
    ('fysioterapeuten.no', 'Fysioterapeuten'),
    ('jaaralexu.journals.ekb.eg', 'Mağallaẗ Taṭbīqāt ʿulūm Al-Rīyāḍaẗ'),
    ('emeraldgrouppublishing.com', 'Tourism Critiques'),
    ('revistaderecho.ucn.cl', 'Revista de Derecho (Coquimbo)'),
    ('journal.uokufa.edu.iq', 'Kufa Journal for Nursing Sciences'),
    ('journals.library.brandeis.edu', 'Caste'),
    ('dalps.tirant.com', 'Derecho Animal'),
    ('eppcgs.org', 'Earth and Planetary Physics'),
    ('jurnal.ugm.ac.id', 'Journal of Internet and Software Engineering'),
    ('qfi-oz.de', 'Qualifizierung für Inklusion'),
    ('linguarumuniverse.weebly.com', 'Linguarum Universe'),
    ('jpl.letras.ulisboa.pt', 'Journal of Portuguese Linguistics'),
    ('sc.journals.umz.ac.ir', 'Journal of Genetic Resources'),
    ('en.china-fishery.cn', 'Shuichan Xuebao'),
    ('ejurnal.teknokrat.ac.id', 'Jurnal Teknoinfo'),
    ('rhema-journal.com', 'Rhema. Рема'),
    ('bmcmedgenomics.biomedcentral.com', 'BMC Medical Genomics'),
    ('ejournal.sttii-yogyakarta.ac.id', 'Predica Verbum'),
    ('revistas.uexternado.edu.co', 'Sotavento MBA'),
    ('arsmedica.cl', 'ARS Medica'),
    ('arabmediasociety.com', 'Arab Media and Society'),
    ('tet.rkk.hu', 'Tér és Társadalom'),
    ('cswr.columbia.edu', 'Columbia Social Work Review'),
    ('ir.library.louisville.edu', 'The University of Louisville Journal of Respiratory Infections'),
    ('iucrdata.iucr.org', 'IUCrData'),
    ('publichealthtoxicology.com', 'Public Health and Toxicology'),
    ('periodicos.ufpb.br', 'Teoria e Prática em Administração'),
    ('ojs.udb.ac.id', 'Jurnal Keperawatan Duta Medika'),
    ('unissa.edu.bn', 'International Journal of \'Umrānic Studies'),
    ('rivista-statistica.unibo.it', 'Statistica'),
    ('jurnal.ar-raniry.ac.id', 'Elkawnie: Journal of Islamic Science and Technology'),
    ('mnase.journals.ekb.eg', 'Maǧallaẗ Naẓariyāt wa Taṭbīqāt Al-Tarbiyyaẗ Al-Badaniyyaẗ waʿulūm Al-Rīyāḍaẗ'),
    ('journals.aua.ke', 'Pan-African Journal of Health and Environmental Science'),
    ('trilogi.ac.id', 'JISA (Jurnal Informatika dan Sains)'),
    ('energy-cie.ro', 'Journal of Sustainable Energy'),
    ('ojs.unito.it', 'Gli Spazi della Musica'),
    ('bmjdigitalhealth.bmj.com', 'BMJ Digital Health & AI'),
    ('revistadigital.uce.edu.ec', 'Revista Textos y Contextos'),
    ('slovenskapediatrija.si', 'Slovenska pediatrija'),
    ('przeglad.amu.edu.pl', 'Przegląd Politologiczny'),
    ('journal.poltekpar-nhi.ac.id', 'Jurnal Kepariwisataan'),
    ('periodicos.claec.org', 'Conexões Culturais'),
    ('arcticandnorth.ru', 'Арктика и Север'),
    ('ssi.journals.umz.ac.ir', 'جامعه‌شناسی نهادهای اجتماعی'),
    ('jtresda.ub.ac.id', 'Jurnal Teknologi dan Rekayasa Sumber Daya Air'),
    ('journals.lub.lu.se', 'Nordidactica: Journal of Humanities and Social Science Education'),
    ('oajournals.fupress.net', 'SocietàMutamentoPolitica: Rivista Italiana di Sociologia'),
    ('embopress.org', 'Molecular Systems Biology'),
    ('journals.univ-temouchent.edu.dz', 'Revue Algérienne des Lettres'),
    ('myrwd.ru', 'Реальная клиническая практика: данные и доказательства'),
    ('journal.unpas.ac.id', 'Journal Sampurasun'),
    ('mdpi.com', 'Biosensors'),
    ('ojs.inidep.edu.ar', 'Marine and Fishery Sciences'),
    ('plutojournals.com', 'Zamani: A Journal of African Historical Studies'),
    ('apgs.ufv.br', 'Administração Pública e Gestão Social'),
    ('jicw.org', 'The Journal of Intelligence, Conflict and Warfare'),
    ('talenta.usu.ac.id', 'Data Science'),
    ('jrpb.unram.ac.id', 'Jurnal Ilmiah Rekayasa Pertanian dan Biosistem'),
    ('ajol.info', 'African Journal of Social Work'),
    ('journal.bcrec.id', 'Journal of Chemical Engineering Research Progress'),
    ('termedia.pl', 'Journal of Health Inequalities'),
    ('journal.asu.ru', 'Society and Security Insights'),
    ('periodicals.karazin.ua', 'Український соціологічний журнал'),
    ('historical-weapons.com', 'Историческое оружиеведение'),
    ('journal.umpo.ac.id', 'Jurnal Indria: Jurnal Ilmiah Pendidikan Prasekolah dan Sekolah Awal'),
    ('pccc.icrc.ac.ir', 'Progress in Color, Colorants and Coatings'),
    ('ejournal.uin-suska.ac.id', 'Jurnal Teknik Industri: Jurnal Hasil Penelitian dan Karya Ilmiah dalam Bidang Teknik Industri'),
    ('scup.com', 'Nordisk Välfärdsforskning'),
    ('rbone.com.br', 'Revista Brasileira de Obesidade, Nutrição e Emagrecimento'),
    ('archeologickerozhledy.cz', 'Archeologické Rozhledy'),
    ('bas.journals.uvt.ro', 'British and American Studies'),
    ('dukeupress.edu', 'Liquid Blackness'),
    ('periodicos.ufes.br', 'Kiri-Kerê'),
    ('iopscience.iop.org', 'Materials for Quantum Technology'),
    ('ejournals.epublishing.ekt.gr', 'Επιθεώρηση Κοινωνικών Ερευνών'),
    ('intelaquares.tonekabon.iau.ir', 'International Aquatic Research'),
    ('sibscript.ru', 'СибСкрипт'),
    ('revistaiberica.org', 'Ibérica'),
    ('revistas.unal.edu.co', 'Momento'),
    ('caip.co-ac.com', 'Materials and Devices'),
    ('ricerchedisconfine.info', 'Ricerche di S/Confine'),
    ('textopoetico.emnuvens.com.br', 'Texto Poético'),
    ('jftonline.org', 'Journal of Financial Therapy'),
    ('journals.muni.cz', 'Sociální studia'),
    ('journal.fi', 'Neuphilologische Mitteilungen'),
    ('autopsyandcasereports.org', 'Autopsy and Case Reports'),
    ('medbiosci.ru', 'Медицина и биотехнологии'),
    ('revistas.ecosur.mx', 'Sociedad y Ambiente'),
    ('pythagoras.org.za', 'Pythagoras'),
    ('studia.reviste.ubbcluj.ro', 'Studia Universitatis Babeş-Bolyai: Educatio Artis Gymnasticae'),
    ('lyellcollection.org', 'Earth Science, Systems and Society'),
    ('ejournal.uinsaizu.ac.id', 'Al-Manahij: Jurnal Kajian Hukum Islam'),
    ('he02.tci-thaijo.org', 'Veterinary Integrative Sciences'),
    ('njtcg.org', 'Nordic Journal of Transitions, Careers and Guidance'),
    ('ejournal.undip.ac.id', 'Jurnal Sejarah Citra Lekha'),
    ('bmcpsychiatry.biomedcentral.com', 'BMC Psychiatry'),
    ('medicinskiglasnik.ba', 'Medicinski Glasnik'),
    ('jhpr.birjand.ac.ir', 'Journal of Horticulture and Postharvest Research'),
    ('medicinamoderna.ro', 'Modern Medicine'),
    ('journals.uct.ac.za', 'Southern Journal of Engineering Education'),
    ('altex.org', 'ALTEX: Alternatives to Animal Experimentation'),
    ('revistes.ub.edu', 'Temps d\'Educació'),
    ('ijltr.urmia.ac.ir', 'Iranian Journal of Language Teaching Research'),
    ('jad.tums.ac.ir', 'Journal of Arthropod-Borne Diseases'),
    ('jci.numl.edu.pk', 'NUML Journal of Critical Inquiry'),
    ('revista.ajrpt.com', 'Argentinian Journal of Respiratory and Physical Therapy'),
    ('journalmechanicalventilation.com', 'Journal of Mechanical Ventilation'),
    ('dpcj.org', 'Dermatology Practical & Conceptual'),
    ('buijhs.journals.ekb.eg', 'Beni-Suef University International Journal of Humanities and Social Sciences'),
    ('sav.sk', 'Slovenska Literatura'),
    ('sciengine.com', 'National Science Open'),
    ('jurnal.usk.ac.id', 'International Journal of Disaster Management'),
    ('degruyter.com', 'Linguistics'),
    ('gvaa.com.br', 'ACTA Apicola Brasilica'),
    ('ejurnal.ung.ac.id', 'Jambura Journal of Mathematics'),
    ('jar.punjab.gov.pk', 'Journal of Agricultural Research'),
    ('revistes.eapc.gencat.cat', 'Revista Catalana de Dret Públic'),
    ('ojs.uv.es', 'Journal of Literary Education'),
    ('jesit.springeropen.com', 'Journal of Electrical Systems and Information Technology'),
    ('revistas.ucm.es', 'Talía'),
    ('tesolal.columbia.edu', 'Studies in Applied Linguistics & TESOL'),
    ('revistas.unc.edu.ar', 'Pensum'),
    ('ijpdtm.it', 'Italian Journal of Prevention Diagnostic and Therapeutic Medicine'),
    ('vtg.mod.gov.rs', 'Vojnotehnički Glasnik'),
    ('opengeomechanics.org', 'Open Geomechanics'),
    ('nic.shahed.ac.ir', 'مطالعات بنیادین تمدن نوین اسلامی'),
    ('ejournals.bc.edu', 'Studies in Christian-Jewish Relations'),
    ('malariajournal.biomedcentral.com', 'Malaria Journal'),
    ('czasopisma.upjp2.edu.pl', 'Folia Historica Cracoviensia'),
    ('ietresearch.onlinelibrary.wiley.com', 'IET Cyber-systems and Robotics'),
    ('fcf.unse.edu.ar', 'Revista Quebracho'),
    ('publicaciones.unirioja.es', 'Brocar. Cuadernos de investigación histórica'),
    ('peren-revues.fr', 'Déméter'),
    ('etrr.springeropen.com', 'European Transport Research Review'),
    ('journal.walisongo.ac.id', 'Daluang'),
    ('ndt.net', 'e-Journal of Nondestructive Testing'),
    ('ejournal.upnvj.ac.id', 'Jurnal Keperawatan Widya Gantari Indonesia'),
    ('digital.kenyon.edu', 'Peregrinations'),
    ('publicaciones.sociales.uba.ar', 'Quid 16'),
    ('jurnal.untan.ac.id', 'Jurnal Ekonomi Bisnis dan Kewirausahaan (JEBIK)'),
    ('dfsr.ir', 'آینده‌پژوهی دفاعی'),
    ('iidentidadess.wordpress.com', 'Identidades'),
    ('link.springer.com', 'Cellular and Molecular Life Sciences'),
    ('mjhs-mu.org', 'Majmaah Journal of Health Sciences'),
    ('brill.com', 'Journal of Chinese Humanities'),
    ('opo.iisj.net', 'Sortuz'),
    ('eap.ee', 'Trames'),
    ('journals.ucn.dk', 'Cepra-Striben'),
    ('jcese.journals.ekb.eg', 'مجلة العلوم التجارية والبيئية'),
    ('bbp4b.litbang.kkp.go.id', 'Jurnal Pascapanen dan Bioteknologi Kelautan dan Perikanan'),
    ('nonpartisaneducation.org', 'Nonpartisan Education Review'),
    ('forointernacional.colmex.mx', 'Foro Internacional'),
    ('jhetonline.com', 'Journal of Health Education Teaching'),
    ('eupublicmarkets.com', 'European Journal of Public Procurement Markets'),
    ('godisnjak.anubih.ba', 'Godišnjak'),
    ('mascvuex.unex.es', 'Revista de Investigación en Didáctica de las Ciencias Sociales'),
    ('gyqx.ac.cn', 'Gaoyuan qixiang'),
    ('sustainenergyres.springeropen.com', 'Renewables: Wind, Water, and Solar'),
    ('ojs.austral.edu.ar', 'Revista Internacional de Derechos Humanos'),
    ('imrpress.com', 'Frontiers in Bioscience-Scholar'),
    ('journals.viamedica.pl', 'Acta Haematologica Polonica'),
    ('njs.libraries.rutgers.edu', 'New Jersey Studies: an Interdisciplinary Journal'),
    ('sobremexico-revista.ibero.mx', 'Sobre México'),
    ('fsu.ua', 'Ribogospodarsʹka Nauka Ukraïni'),
    ('seer.ufs.br', 'Prometeus: Filosofia em Revista'),
    ('joemls.dils.tku.edu.tw', 'Jiàoyù zīliào yǔ túshūguǎn xué'),
    ('journal.ubpkarawang.ac.id', 'Buana Information Technology and Computer Sciences'),
    ('jst-ud.vn', 'Tạp chí Khoa học và Công nghệ'),
    ('riuq.uniquindio.edu.co', 'Revista de Investigaciones Universidad del Quindío'),
    ('pjaec.pk', 'Pakistan Journal of Analytical & Environmental Chemistry'),
    ('edj.hmu.edu.krd', 'Erbil Dental Journal'),
    ('revistas.uned.es', 'Elia'),
    ('vestnik-hss.kemsu.ru', 'Вестник Кемеровского государственного университета. Серия: гуманитарные и общественные науки'),
    ('iraqmedj.org', 'Iraq Medical Journal'),
    ('bmccomplementmedtherapies.biomedcentral.com', 'BMC Complementary Medicine and Therapies'),
    ('revistas.udea.edu.co', 'Vitae'),
    ('revistas.ugm.cl', 'Akadèmeia'),
    ('mi-dnu.dp.ua', 'European Journal of Management Issues'),
    ('rbes.fa.ru', 'Review of Business and Economics Studies'),
    ('noaj.org.np', 'Nepal Orthopedic Association Journal'),
    ('revistas.unicartagena.edu.co', 'Perspectivasafro'),
    ('journals.sabauni.edu.ge', 'Orbeliani Law Review'),
    ('revistaseletronicas.pucrs.br', 'Veritas'),
    ('akjournals.com', 'Scientia et Securitas'),
    ('educar.uab.cat', 'Educar'),
    ('mij.areeo.ac.ir', 'Mycologia Iranica'),
    ('jurnal.uns.ac.id', 'Agricultural Socio-Economic Empowerment and Agribusiness Journal'),
    ('ajmc.aut.ac.ir', 'AUT Journal of Mathematics and Computing'),
    ('bsmiab.org', 'Plant Trends'),
    ('expresioneconomica.cucea.udg.mx', 'Expresión Económica'),
    ('ajps.uomustansiriyah.edu.iq', 'Al-Mustansiriyah Journal of Pharmaceutical Sciences'),
    ('journal.uinsgd.ac.id', 'Khazanah Pendidikan Islam'),
    ('revistas.uncu.edu.ar', 'Cuadernos de Historia del Arte'),
    ('revistas.uclave.org', 'Mayéutica: Revista Científica de Humanidades y Artes'),
    ('journals.iucr.org', 'Acta Crystallographica Section E'),
    ('revistas.usb.edu.co', 'Ingenierías USBMed'),
    ('banglajol.info', 'Journal of Scientific Research'),
    ('aet.irost.ir', 'Advances in Environmental Technology'),
    ('revistas.pucp.edu.pe', '360'),
    ('perfilesla.flacso.edu.mx', 'Perfiles Latinoamericanos'),
    ('online.unisc.br', 'Signo'),
    ('academia.edu', 'Academia Molecular Biology and Genomics'),
    ('journals.elsevier.com', 'Journal of Power Sources Advances'),
    ('revistas.udb.edu.sv', 'Diá-logos'),
    ('periodicos.fundaj.gov.br', 'Ciência & Trópico'),
    ('hsew.journals.ekb.eg', 'حولية سمنار التاريخ الإسلامى والوسيط'),
    ('qjes.qu.edu.iq', 'Al-Qadisiyah Journal for Engineering Science'),
    ('moderna.historicas.unam.mx', 'Estudios de Historia Moderna y Contemporánea de México'),
    ('ims.atu.ac.ir', 'مطالعات مدیریت کسب و کار هوشمند'),
    ('ijeee.edu.iq', 'Iraqi Journal for Electrical and Electronic Engineering'),
    ('eneuro.org', 'eNeuro'),
    ('ojs.literacyinstitute.org', 'International Journal of Qualitative Research'),
    ('constructions-journal.com', 'Constructions'),
    ('seer.fclar.unesp.br', 'Doxa'),
    ('vokasindo.ub.ac.id', 'Vok@Sindo: Jurnal Ilmu-Ilmu Terapan dan Hasil Karya Nyata'),
    ('worldscientific.com', 'Journal of Advanced Dielectrics'),
    ('journal.upgris.ac.id', 'Jurnal informatika UPGRIS'),
    ('vjtm.vanguardcollege.com', 'Vanguard Journal of Theology & Ministry'),
    ('periodicos.ufc.br', 'Revista de Ciências Sociais'),
    ('ojs.revistamaternofetal.com', 'Revista Internacional de Salud Materno Fetal'),
    ('revue.ummto.dz', 'الخطاب'),
    ('polimery.umw.edu.pl', 'Polimery w Medycynie'),
    ('e-journals.ku.lt', 'Computational Science and Techniques'),
    ('jnamt.org', 'Journal of Naval Architecture and Marine Technology'),
    ('anales.fisica.org.ar', 'Anales (Asociación Física Argentina)'),
    ('japhac.wix.com', 'Journal of Applied Pharmaceutical Sciences'),
    ('riviste.unimi.it', 'Rivista di studi e ricerche sulla criminalità organizzata'),
    ('pubs.ufs.ac.za', 'Interdisciplinary Journal of Rural and Community Studies'),
    ('jart.guilan.ac.ir', 'Journal of Algebra and Related Topics'),
    ('iflorestal.sp.gov.br', 'Revista do Instituto Florestal'),
    ('ijict.itrc.ac.ir', 'International Journal of Information and Communication Technology Research'),
    ('revistas.udc.es', 'Sportis'),
    ('fmp.elpub.ru', 'Вестник Московского Университета. Серия XXV: Международные отношения и мировая политика'),
    ('conexoes.ifce.edu.br', 'Conexões: Ciência e Tecnologia'),
    ('revistadedreptconstitutional.ro', 'Revista de Drept Constituţional'),
    ('ia.spcras.ru', 'Информатика и автоматизация'),
    ('zgds.si', 'Gozdarski Vestnik'),
    ('press.wz.uw.edu.pl', 'Journal of Marketing and Consumer Behaviour in Emerging Markets'),
    ('iqjfmme.com', 'Iraqi Journal for Mechanical and Materials Engineering'),
]

BEALLS_JOURNALS = [
    ('1088.email', '1088 Email Press'),
    ('2425publishers.org', '2425 Publishers'),
    ('5thpublisher.com', 'The 5th Publisher'),
    ('abcjournals.net', 'ABC Journals'),
    ('ampublisher.com', 'A M Publishers'),
    ('abhinavjournal.com', 'Abhinav'),
    ('academeresearchjournals.org', 'Academe Research Journals'),
    ('academiapublishing.org', 'Academia Publishing'),
    ('academiaresearch.org', 'Academia Research'),
    ('academiascholarlyjournal.org', 'Academia Scholarly Journals'),
    ('aabri.com', 'Academic and Business Research Institute'),
    ('acascipub.com', 'Academic and Scientific Publishing'),
    ('ph.academicdirect.org', 'Academic Direct Publishing House'),
    ('academicjournals.org', 'Academic Journals'),
    ('acjar.org', 'Academic Journals and Research'),
    ('academicjournalsonline.co.in', 'Academic Journals Online'),
    ('academicjournalsinc.com', 'Academic Journals, Inc.'),
    ('akrpub.com', 'Academic Knowledge and Research Publishing'),
    ('academicoasis.org', 'Academic Organization for Advancement of Strategic and International Studies'),
    ('acadpubl.eu', 'Academic Publications, Ltd.'),
    ('arseam.com', 'Academic Research in Science, Engineering, Art and Management'),
    ('academicresearchjournals.org', 'Academic Research Journals'),
    ('acrpub.com', 'Academic Research Publishers'),
    ('arpapress.com', 'Academic Research Publishing Agency'),
    ('arpgweb.com', 'Academic Research Publishing Group'),
    ('acadrp.org', 'Academic Research Publishing House'),
    ('academic-publishing-house.com', 'Academic Scholars Publishing House'),
    ('ijaponline.org', 'Academic Sciences'),
    ('academicstar.us', 'Academic Star Publishing Company'),
    ('astarstore.us', 'Academic Star Publishing Company [alt]'),
    ('academicwebpublishers.org', 'Academic Web Publishers'),
    ('awer-center.org', 'Academic World Education & Research Center'),
    ('arcjournals.org', 'Academicians’ Research Center/ARC Journals'),
    ('academicsworld.org', 'Academics World'),
    ('aelsindia.com', 'Academy for Environment and Life Sciences'),
    ('academyjournals.net', 'Academy Journals'),
    ('abrmr.com', 'Academy of Business & Retail Management'),
    ('absronline.org', 'Academy of Business & Scientific Research'),
    ('academyirmbr.com', 'Academy of International Research in Management and Business Realities'),
    ('akpinsight.webs.com', 'Academy of Knowledge Process'),
    ('scienceengineeringacademy.org', 'Academy of Science and Engineering'),
    ('asss-web.com', 'Academy of Science and Social Science'),
    ('asaarjournals.com', 'Academy of Scientific and Applied Research'),
    ('academypublish.org', 'Academy Publish'),
    ('accessinterjournals.org', 'Access International Journals'),
    ('accessjournals.org', 'Access Journals'),
    ('accesspublishers.org', 'Access Publishers'),
    ('ghrnet.org', 'ACT Publishing'),
    ('actascientifica.com', 'Acta Scientifica'),
    ('adpublication.org', 'AD Publication'),
    ('adpublications.org', 'AD Publications'),
    ('ada-lovelace.co.uk', 'Ada Lovelace Publications'),
    ('aeirc-edu.com', 'Advance Educational Institute & Research Centre'),
    ('advancejournals.org', 'Advance Journals'),
    ('aicit.org', 'Advanced Institute of Convergence Information Technology'),
    ('advancedjournals.org', 'Advanced Journals'),
    ('advancedresearchjournals.org', 'Advanced Research Journals'),
    ('adrpublications.in', 'Advanced Research Publications'),
    ('advancedscholarsjournals.org', 'Advanced Scholars Journals'),
    ('asetrc.org', 'Advanced Science and Engineering Technology Institute'),
    ('advancedscienceresearchjournals.org', 'Advanced Science Research Journals'),
    ('atscience.org', 'Advanced Technology & Science'),
    ('aditisci.com', 'Advancement and Development in Technology International'),
    ('ajournals.com', 'Advancements in Science'),
    ('adyanacademicpress.com', 'Adyan Academic Press'),
    ('aensiweb.com', 'American-Eurasian Network for Scientific Information'),
    ('afrrevjo.net', 'African Research Review'),
    ('agialpress.com', 'AgiAl Publishing House'),
    ('agropub.com', 'Agropub'),
    ('ainstin.com', 'AINSTIN Knowledge Hub'),
    ('airccse.org', 'AIRCC Publishing Corporation'),
    ('aizeonpublishers.net', 'Aizeon Publishers'),
    ('albertscience.com', 'Albert Science International Organization'),
    ('alliedacademies.org', 'Allied Academies'),
    ('alliedjournals.com', 'Allied Journals'),
    ('ambitjournals.org', 'Ambit Journals'),
    ('amepc.org', 'AME Publishing Company'),
    ('aasrc.org', 'American Academic & Scholarly Research Center'),
    ('aascit.org', 'American Association for Science and Technology'),
    ('amjournals.org', 'American Journal'),
    ('aripd.org', 'American Research Institute for Policy Development'),
    ('arjonline.org', 'American Research Journals'),
    ('arepub.com', 'American Research Publications'),
    ('asraresearch.org', 'American Scholarly Research Association'),
    ('aspbs.com', 'American Scientific Publishers'),
    ('americanscientificresearchjournals.org', 'American Scientific Research Journals'),
    ('asrn.org', 'American Society of Registered Nurses'),
    ('as-se.org', 'American Society of Science and Engineering'),
    ('vkingpub.com', 'American V-King Scientific Publishing'),
    ('aessangli.in', 'Amoghsiddhi Education Society/AES/AES Journals in Engineering Technology, Management, and Sciences/AES E-JOURNALS'),
    ('ejournal.aessangli.in', 'Amoghsiddhi Education Society/AES/AES Journals in Engineering Technology, Management, and Sciences/AES E-JOURNALS [alt]'),
    ('andrewjohnpublishing.org', 'Andrew John Publishing Inc.'),
    ('annexpublishers.com', 'Annex Publishers'),
    ('ansinet.com', 'Asian Network for Scientific Information'),
    ('domainsmoon.com', 'Antarctic Journals'),
    ('aperito.org', 'Aperito Online Publishing'),
    ('apexjournal.org', 'Apex Journal'),
    ('applied-science-innovations.com', 'Applied Science Innovations'),
    ('apst.co.in', 'APST Publication'),
    ('arabianjbmr.com', 'Arabian Group of Journals'),
    ('puneresearch.com', 'Aradhya International Publication'),
    ('aeph.in', 'Archers & Elevators Publishing House'),
    ('archyworld.com', 'Archyworld'),
    ('arpnjournals.com', 'ARPN Journals'),
    ('aspublishers.com', 'AS Publishers'),
    ('asdpub.com', 'ASD Publisher'),
    ('ashdin.com', 'Ashdin Publishing'),
    ('ashese.co.uk', 'AshEse Visionary'),
    ('apamr.org', 'Asia-Pacific Association of Medical Research'),
    ('apiar.org.au', 'Asia Pacific Institute of Advanced Research'),
    ('asianacademicresearch.org', 'Asian Academic Research Associates'),
    ('aarpub.com', 'Asian and American Research Publishing Group'),
    ('aessweb.com', 'Asian Economic and Social Society'),
    ('asianonlinejournals.com', 'Asian Online Journal Publishing Group'),
    ('ajouronline.com', 'Asian Online Journals'),
    ('asianpharmaonline.org', 'Asian Pharma Press'),
    ('asianpubs.org', 'Asian Publication Corporation'),
    ('aijsh.org', 'Asian Research Consortium'),
    ('asian-transactions.org', 'Asian Transactions'),
    ('aarf.asia', 'Associated Asia Research Foundation'),
    ('asers.eu', 'Association for Sustainable Education, Research and Science'),
    ('theaceee.org', 'Association of Computer Electronics and Electrical Engineers'),
    ('anahei.org', 'Association of North America Higher Education International'),
    ('asterpublications.org', 'Aster Publications'),
    ('astonjournals.com', 'AstonJournals'),
    ('athalgroup.com', 'Athal Press & Media'),
    ('atharvapub.com', 'Atharva Scientific Publications'),
    ('atiner.gr', 'Athens Institute for Education and Research'),
    ('atlas-publishing.org', 'Atlas Publishing, LP'),
    ('chesci.com', 'Aufau Periodicals'),
    ('austinpublishinggroup.org', 'Austin Publishing Group'),
    ('acrd.net.au', 'Australasian Centre for Research and Development'),
    ('aabss.org.au', 'Australian Academy of Business and Social Sciences'),
    ('aabl.com.au', 'Australian Academy of Business Leadership'),
    ('aiac.org.au', 'Australian International Academic Centre Pty. Ltd.'),
    ('ausinternationaljournals.com.au', 'Australian International Research Consortium'),
    ('scie.org.au', 'Australian Society for Commerce Industry & Engineering'),
    ('aeuso.org', 'Austrian E-Journals of Universal Scientific Organization'),
    ('autpub.org', 'Austrian Scientific Publication House'),
    ('avantipublishers.com', 'Avanti Publishers.com'),
    ('avensonline.org', 'Avens Publishing Group'),
    ('avestia.com', 'Avestia Publishing'),
    ('avicenapublisher.org', 'Avicena Publisher'),
    ('avidscience.com', 'Avid Science'),
    ('axisjournals.com', 'Axis Journals'),
    ('wjgnet.com', 'Baishideng Publishing Group'),
    ('basharesearch.com', 'Basha Research Corporation'),
    ('basicresearchjournals.org', 'Basic Research Journals'),
    ('bellpress.org', 'Bell Press'),
    ('benthamopen.com', 'Bentham Open'),
    ('bestjournals.in', 'Best Journals'),
    ('bapress.ca', 'Better Advances Press'),
    ('bettyjonespub.com', 'Betty Jones & Sisters Publishing'),
    ('1010press.com', 'Binary Information Press'),
    ('bioaccent.org', 'Bio Accent/Bioaccent'),
    ('biocoreopen.org', 'Bio Core/Biocore'),
    ('bioflux.com.ro', 'Bioflux Society'),
    ('biohelikon.org', 'Biohelikon'),
    ('biohouse.us', 'Biohouse Publishing Group'),
    ('bioinfopublication.org', 'BioInfo Publications'),
    ('bipublication.com', 'BioIT international Journals'),
    ('bacpl.org', 'Biological and Chemical Publishing'),
    ('biomedpress.org', 'BioMed Press'),
    ('bmrjournals.com', 'BioMed Research'),
    ('biomedscidirect.com', 'BioMedSciDirect Publications'),
    ('biopublisher.ca', 'BioPublisher'),
    ('bret.ac.in', 'Bioscience Research & Educational Institute [Link dead as of 2012-11-14]'),
    ('blazejournals.org', 'Blaze Journals'),
    ('blue-ap.org', 'Blue Apple Publications'),
    ('blueeyesintelligence.org', 'Blue Eyes Intelligence Engineering & Sciences Publication'),
    ('borjournals.com', 'Blue Ocean Research Journals'),
    ('bluepenjournals.org', 'BluePen Journals'),
    ('bonfring.org', 'Bonfring'),
    ('bowenpublishing.com', 'Bowen Publishing'),
    ('brainybuzz.in', 'Brainy Buzz'),
    ('bretj.com', 'Bret Research Journals'),
    ('bjmhs.baar.org.uk', 'British Association of Academic Research'),
    ('bjournal.co.uk', 'British Journal'),
    ('borpub.com', 'British Open Research Publications'),
    ('brnsspublicationhub.org', 'BRNSS Publication Hub'),
    ('businessjournalz.org', 'Business Journalz'),
    ('bizmanagementcentre.com', 'Business Management Centre'),
    ('businessperspectives.org', 'Business Perspectives'),
    ('cafetinnova.org', 'Cafet Innova Technical Society'),
    ('cdbenchmark.com', 'Cairo Center for Development Benchmarking'),
    ('cscanada.net', 'CSCanada'),
    ('ccsenet.org', 'Canadian Center of Science and Education'),
    ('crpub.com', 'Canadian Research Publication'),
    ('cansrg.com', 'Canadian Science and Research Group'),
    ('canadianstpress.com', 'Canadian Science and Technology Press Inc.'),
    ('cardiologyacademicpress.com', 'Cardiology Academic Press'),
    ('carijournals.org', 'CARI Journals'),
    ('cenetrionline.org', 'Cenetri Publishing Group'),
    ('cekinfo.org.uk', 'Center for Enhancing Knowledge'),
    ('cgrd.org', 'Center for Global Research Development'),
    ('cibmp.org', 'The Center for Innovations in Business & Management Practice'),
    ('cennser.org', 'Center for Natural Science & Engineering Research'),
    ('cpinet.info', 'Center for Promoting Ideas'),
    ('cddk.org', 'Center for the Development and Dissemination of Knowledge'),
    ('casrp.co.uk', 'Center of Advanced Scientific Research and Publications'),
    ('journals.cz', 'Central Bohemia University Publishing'),
    ('cri.ideainfinity.pk', 'Central Research Insight'),
    ('cibtech.org', 'Centre For Info Bio Technology'),
    ('c-mric.org', 'Centre for Multidisciplinary Research, Innovation and Collaboration'),
    ('ijsrit.com', 'Centre for Promoting Knowledge'),
    ('centreofexcellence.net', 'Centre of Excellence for Scientific & Research Journalism'),
    ('cprenet.com', 'Centre of Promoting Research Excellence'),
    ('ceser.in', 'CESER Publications'),
    ('chitkara.edu.in', 'Chitkara University Publications'),
    ('cirworld.com', 'CIRWORLD'),
    ('clerisyonlinepublishers.org', 'Clerisy Publishers'),
    ('clinmedjournals.org', 'ClinMed International Library'),
    ('cloud-journals.com', 'Cloud Journals'),
    ('cloudpublications.org', 'Cloud Publications'),
    ('cluteinstitute.com', 'The Clute Institute'),
    ('clytoaccess.com', 'Clyto Access'),
    ('coltharpinstitute.com', 'Coltharp Institute'),
    ('uscip.org', 'Columbia International Publishing'),
    ('comparativejournals.org', 'Comparative Journals'),
    ('comprehensiveresearchjournals.org', 'Comprehensive Research Journals'),
    ('cscjournals.org', 'Computer Science Journals'),
    ('confabjournals.com', 'CONFAB Journals'),
    ('congresspress.com', 'Congress Press'),
    ('icdtdi.ca', 'CONSORTIUM Intellectual Consortium of Drug Discovery and Technology Development, Inc.'),
    ('ijern.com', 'Contemporary Research Center'),
    ('globalcis.org', 'Convergence Information Society'),
    ('cosmicjournals.com', 'Cosmic Journals'),
    ('cosmosscholars.com', 'Cosmos Scholars Publishing House'),
    ('cirworld.net', 'Council for Innovative Research'),
    ('crdeep.com', 'CRDEEP International Journals'),
    ('crescopublications.org', 'Cresco Online Publishing'),
    ('crescoonline.org', 'Cresco Online Publishing [alt]'),
    ('crestjournals.com', 'CREST Journals'),
    ('crownjournals.org', 'Crown Journals'),
    ('tcrjournals.com', 'CTR Publications'),
    ('curresweb.com', 'Current Research Web'),
    ('cyberjournals.com', 'Cyber Journals'),
    ('sciencejournal.in', 'DAMA International'),
    ('darsgah-e-ahlebait.com', 'Darsgah-e-Ahlebait'),
    ('darshanpublishers.com', 'Darshan Publishers'),
    ('davidpublishing.com', 'David Publishing'),
    ('davidpublisher.org', 'David Publishing [alt]'),
    ('deccanpharmajournals.com', 'Deccan Pharma Journals'),
    ('denovojournal.com', 'DeNovo Scientific Publishing'),
    ('dentamedpublishing.com', 'Dentamed Publishing'),
    ('sign-ific-ance.co.uk', 'Design for Scientific Renaissance'),
    ('destechpub.com', 'DEStech Publications, Inc.'),
    ('dcthink.org', 'Developing Country Think Tank Institute'),
    ('dhanmedpublishers.com', 'Dhan Med Publishers'),
    ('didacticjournals.org', 'Didactic Journals'),
    ('dirf.org', 'Digital Information Research Foundation'),
    ('dscipress.com', 'Digital Science Press'),
    ('directresearchpublisher.org', 'Direct Research Journals'),
    ('disa.org.in', 'DISA Publication Group'),
    ('resjournals.org', 'Discourse Journals'),
    ('discoveryjournals.com', 'Discovery Publication'),
    ('djjames.org', 'DJ Publications'),
    ('donnishjournals.org', 'Donnish Journals'),
    ('dormaj.com', 'Dorma Journals'),
    ('drbgrpublications.in', 'Dr.BGR Publications'),
    ('drunpp.ba', 'DRUNPP Sarajevo'),
    ('dynamicpublishers.org', 'Dynamic Publishers'),
    ('e-century.org', 'e-Century Publishing Corporation'),
    ('ecronicon.com', 'E-Cronicon'),
    ('worldresearchjournals.com', 'e-journal'),
    ('shankargargh.org', 'e-journal [alt]'),
    ('esciencecentral.org', 'e-Science Central'),
    ('e3journals.org', 'e3Journals'),
    ('eaglegp.org', 'Eagle Publishing Group'),
    ('earthjournals.org', 'Earth Journals'),
    ('ew-a.org', 'East West Association For Advanced Studies and Higher Education'),
    ('ebioscholar.com', 'Ebioscholar'),
    ('ebupress.com', 'Ebu Press'),
    ('ecanadianjournals.com', 'eCanadian Journals'),
    ('econjournals.com', 'Econjournals'),
    ('tesdo.org', 'The Economics and Social Development Organization'),
    ('edelweisspublications.com', 'Edelweiss Publications'),
    ('edugait.com', 'EDUGAIT Press'),
    ('eijasr.com', 'E-International Journals of Academic & Scientific Research'),
    ('eisrjc.com', 'E-International Scientific Research Journal Consortium'),
    ('internationaljournalesrg.org', 'Eighth Sense Research Group'),
    ('eijo.in', 'Einstein International Journal Organization'),
    ('ejmscience.com', 'eJM Science, eJManager'),
    ('ejarr.com', 'eJournals of Academic Research & Reviews'),
    ('ekojournal.com', 'Eko Journal'),
    ('theelearninginstitute.org', 'eLearning Institute'),
    ('ecisi.com', 'Electronic Center for International Scientific Information'),
    ('m.elewa.org', 'Elewa Bio Sciences'),
    ('elitehall.elitehall.com', 'Elite Hall Publishing House'),
    ('eliteresearchjournals.org', 'Elite Research Journals'),
    ('elkjournals.com', 'ELK Asia Pacific Journals'),
    ('science-fellows.org', 'ElmCore Journals'),
    ('elmerpress.com', 'Elmer Press'),
    ('elvedit.com', 'ELVEDIT.COM'),
    ('elynsgroup.com', 'Elyns Publishing Group'),
    ('emergingresource.org', 'Emerging Academy Resources'),
    ('etpub.com', 'Engineering and Technology Publishing'),
    ('enggjournals.com', 'Engineering Journals/Engg Journals Publications'),
    ('ephjournal.com', 'Engineering Publication House'),
    ('erpublication.org', 'Engineering Research Publication'),
    ('erpublications.com', 'Enhanced Research Publications'),
    ('enlivenarchive.org', 'Enliven Archive'),
    ('printjournals.com', 'Enriched Science Publication'),
    ('enviropublishers.com', 'Enviro Publishers'),
    ('researchersworld.com', 'ERM Publications/Educational Research Multimedia & Publications'),
    ('epixpub.com', 'EPIX PUB'),
    ('eprajournals.com', 'EPRA Journals'),
    ('eprawisdom.com', 'EPRA Wisdom'),
    ('eruditejournals.org', 'Erudite Journals Limited'),
    ('esrsa.org', 'ESRSA Publication — Engineering and Science Research Support Academy'),
    ('escijournals.net', 'ESci Journals Publishing'),
    ('escipub.com', 'eScience Publisher'),
    ('etamaths.com', 'ETA Maths Journals'),
    ('ethanpublishing.com', 'Ethan Publishing Company'),
    ('eurasianacademy.org', 'Eurasian Academy of Sciences'),
    ('eurasianpublications.com', 'Eurasian Publications'),
    ('erepub.com', 'Eurasian Research Publishing'),
    ('euroasia-science.ru', 'Eurasian Union of Scientists'),
    ('euroasiapub.org', 'Euro Asia Research and Development Association'),
    ('eurojournals.com', 'EuroJournals'),
    ('ea-journals.org', 'European-American Journals'),
    ('euser.org', 'European Center for Science Education and Research'),
    ('ejobm.org', 'European Journals of Business Management'),
    ('oapub.org', 'European Journals of Education Studies'),
    ('europe-science.com', 'The European Scientific Community'),
    ('eurpub.com', 'European Union Research Publishing'),
    ('everant.in', 'Everant'),
    ('everscience.org', 'EverScience Publications'),
    ('ojs.excelingtech.co.uk', 'ExcelingTech Publishing Company, Ltd.'),
    ('excellentpublishers.com', 'Excellent Publishers'),
    ('excellentwordjournals.org', 'Excellent Word Journals'),
    ('excelyticspublishers.com', 'Excelytics Publishers'),
    ('expertjournals.com', 'Expert Journals'),
    ('fareastjournals.com', 'Far East Research Centre'),
    ('ficuspublishers.com', 'Ficus Publishers'),
    ('onlinejournal.in', 'Finlogy'),
    ('firepubs.com', 'Focus in Research & Education/Firepubs'),
    ('fopras.org', 'Foundation for Promotion of Basic & Applied Science'),
    ('fspublishers.org', 'Friends Science Publishers'),
    ('bioscience.org', 'Frontiers in Bioscience'),
    ('fssh-journal.org', 'FSSH Scholarly Journals'),
    ('fundamentaljournals.org', 'Fundamental Journals'),
    ('frdint.com', 'Fundamental Research and Development International'),
    ('futureacademy.org.uk', 'Future Academy'),
    ('gkpublication.in', 'Galore Knowledge Publication Pvt. Ltd.'),
    ('gathacognition.com', 'Gatha Cognition'),
    ('gavinpublishers.org', 'Gavin Publishers'),
    ('gbspublisher.com', 'GBS Publishers & Distributors'),
    ('gpublication.com', 'Genexcellence Publication/G Publications'),
    ('grsci-techpress.org', 'German Science and Technology Press'),
]
